"""recreate artifacts table with new enums

Revision ID: 129726075495
Revises: 5fb79decabb8
Create Date: 2026-06-25 02:28:58.215244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '129726075495'
down_revision: Union[str, Sequence[str], None] = '5fb79decabb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('QUIZ', 'FLASHCARDS', 'FAQ', 'STUDY_GUIDE', 'SUMMARY', 'MINDMAP', 'SLIDE_DECK', name='artifacttype'), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'READY', 'ERROR', name='artifactstatus'), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('included_sources', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.create_index('ix_artifacts_included_sources', 'artifacts', ['included_sources'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_artifacts_notebook_id'), 'artifacts', ['notebook_id'], unique=False)
    op.create_index(op.f('ix_artifacts_user_id'), 'artifacts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_user_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_notebook_id'), table_name='artifacts')
    op.drop_index('ix_artifacts_included_sources', table_name='artifacts', postgresql_using='gin')
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
