"""make some chnages in artifacts model

Revision ID: 5fb79decabb8
Revises: 29becd6ba34b
Create Date: 2026-06-25 02:14:30.402569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fb79decabb8'
down_revision: Union[str, Sequence[str], None] = '29becd6ba34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('included_sources', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('artifacts', sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_index('ix_artifacts_included_sources', 'artifacts', ['included_sources'], unique=False, postgresql_using='gin')
    op.drop_column('artifacts', 'generation_prompt')
    op.drop_column('artifacts', 'source_filter_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('source_filter_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('artifacts', sa.Column('generation_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_artifacts_included_sources', table_name='artifacts', postgresql_using='gin')
    op.drop_column('artifacts', 'context_metadata')
    op.drop_column('artifacts', 'included_sources')
    # ### end Alembic commands ###
