"""drop unique constraint on source_id

Revision ID: 6030bd3aa108
Revises: d4fbc7c85e12
Create Date: 2026-06-21 19:30:02.067441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6030bd3aa108'
down_revision: Union[str, Sequence[str], None] = 'd4fbc7c85e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_source_id'), table_name='sources')
    op.create_index(op.f('ix_sources_source_id'), 'sources', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_source_id'), table_name='sources')
    op.create_index(op.f('ix_sources_source_id'), 'sources', ['source_id'], unique=True)
    # ### end Alembic commands ###
