"""add evidence_pack_json to artifacts

Revision ID: a16c9e3b8504
Revises: 129726075495
Create Date: 2026-06-30 10:46:15.214968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a16c9e3b8504'
down_revision: Union[str, Sequence[str], None] = '129726075495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('evidence_pack_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('artifacts', 'status',
               existing_type=postgresql.ENUM('PROCESSING', 'READY', 'ERROR', name='artifactstatus'),
               nullable=False)
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('artifacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('artifacts', 'status',
               existing_type=postgresql.ENUM('PROCESSING', 'READY', 'ERROR', name='artifactstatus'),
               nullable=True)
    op.drop_column('artifacts', 'evidence_pack_json')
    # ### end Alembic commands ###
